In [5]:
import os
import yaml

import numpy as np
from stl import mesh

# bounding_box_filename = '/home/tmn/ws_caric/src/caric_mission/models/mbs/bounding_boxes/box_description.yaml'
# bounding_box_filename = '/home/tmn/ws_caric/src/caric_mission/models/hangar/bounding_boxes/box_description.yaml'
bounding_box_filename = '/home/tmn/ws_caric/src/caric_mission/models/crane/bounding_boxes/box_description.yaml'

def generate_stl_box(center, size, orientation, filename):
    
    # Calculate the half sizes
    half_sizes = size / 2.0
    
    # Define the eight vertices of the rectangle
    vertices = np.array([ [-half_sizes[0], -half_sizes[1], -half_sizes[2]],
                          [ half_sizes[0], -half_sizes[1], -half_sizes[2]],
                          [ half_sizes[0],  half_sizes[1], -half_sizes[2]],
                          [-half_sizes[0],  half_sizes[1], -half_sizes[2]],
                          [-half_sizes[0], -half_sizes[1],  half_sizes[2]],
                          [ half_sizes[0], -half_sizes[1],  half_sizes[2]],
                          [ half_sizes[0],  half_sizes[1],  half_sizes[2]],
                          [-half_sizes[0],  half_sizes[1],  half_sizes[2]]
                        ])

    # Rotate the vertices around the center
    rotation_matrix = orientation
    rotated_vertices = np.dot(vertices, rotation_matrix.T)

    # Translate the rotated vertices to the center position
    translated_vertices = rotated_vertices + center

    # Create the mesh, each triang has two sides
    faces = np.array([
                        # Bottom face
                        [0, 1, 2],
                        [0, 2, 3],
                        [0, 2, 1],
                        [0, 3, 2],
                        # Top face
                        [4, 5, 6],
                        [4, 6, 7],
                        [4, 6, 5],
                        [4, 7, 6],
                        # Side faces
                        [0, 1, 5],
                        [0, 4, 5],
                        [0, 5, 1],
                        [0, 5, 4],
                        [1, 2, 6],
                        [1, 5, 6],
                        [1, 6, 2],
                        [1, 6, 5],
                        [2, 3, 7],
                        [2, 6, 7],
                        [2, 7, 3],
                        [2, 7, 6],
                        [3, 0, 4],
                        [3, 7, 4],
                        [3, 4, 0],
                        [3, 4, 7]
                     ])

    # Create the STL mesh object
    mesh_data = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))
    for i, face in enumerate(faces):
        for j, vertex_index in enumerate(face):
            mesh_data.vectors[i][j] = translated_vertices[vertex_index]

    # Save the mesh as an STL file
    mesh_data.save(filename)

In [6]:
f = open(bounding_box_filename, "r")
boxes = yaml.safe_load(f)

for box in boxes:
    center      = boxes[box]['center']
    size        = boxes[box]['size']
    orientation = np.array(boxes[box]['orientation']).reshape(4, 4)
    
    print("box name: ",   center     )
    print("box size: ",   size       )
    print("box orie: \n", orientation)

    generate_stl_box(np.array(center), np.array(size), orientation[0:3, 0:3],
                     os.path.dirname(bounding_box_filename) + '/' + box + '.stl')


box name:  [0.85593033, 2.27419472, 40.69194031]
box size:  [10.59708786, 14.95928192, 77.63102722]
box orie: 
 [[ 1.          0.          0.          0.85593033]
 [ 0.          1.          0.          2.27419472]
 [ 0.          0.          1.         40.69194031]
 [ 0.          0.          0.          1.        ]]
box name:  [17.59936523, 2.27419472, 69.27125549]
box size:  [83.34454346, 14.95928192, 8.35]
box orie: 
 [[ 1.          0.          0.         17.59936523]
 [ 0.          1.          0.          2.27419472]
 [ 0.          0.          1.         69.27125549]
 [ 0.          0.          0.          1.        ]]
box name:  [45.91313934, 0.77414036, 35.03113174]
box size:  [10.58403015, 12.43497658, 60.8962326]
box orie: 
 [[ 1.          0.          0.         45.91313934]
 [ 0.          1.          0.          0.77414036]
 [ 0.          0.          1.         35.03113174]
 [ 0.          0.          0.          1.        ]]
box name:  [46.11861038, -28.1302948, 48.10092163]
box 